site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
site_description: Project documentation with MkDocs.
site_author: daizutabi
site_dir: ../pheasant-site/site

repo_url: https://github.com/daizutabi/pheasant/
edit_uri: ""

# theme: ivory
theme: readthedocs

plugins:
  - search
  - pheasant:
      version: pheasant
      nav_number: true

nav:
  - Pheasant: index.md
  - User Guide:
    - Images: user-guide/images.md
    - Embed: user-guide/embed.md
    - SymPy: user-guide/sympy.md
    - Script: user-guide/script.py
    - Cell: user-guide/cell.py
    - user-guide/kernel.md
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
