site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
repo_url: https://github.com/daizutabi/pheasant/

theme:
  name: rtd-pheasant

plugins:
  - pheasant

nav:
  - Home: index.md
  # - Test: test.md
  # - Test2: test2.md

# markdown_extensions:
#   - admonition
#   - attr_list
#   - pymdownx.arithmatex
