site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
repo_url: https://github.com/daizutabi/pheasant/
edit_uri: https://github.com/daizutabi/pheasant/docs/docs/

theme:
  name: readthedocs

extra:
  search:
    language: 'en'

extra_css:
  - css/pheasant.css

markdown_extensions:
  - admonition
  # - codehilite
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - pheasant:
      macro:
        enabled: True
      jupyter:
        kernel_name: {'python': 'doc'}
        sys_paths: ['scripts']
        import_modules: ['hello']
        init_codes: ['import matplotlib as mpl',
                     'import matplotlib.pyplot as plt',
                     'import pandas as pd']
        enabled: True
      number:
        enabled: True
        level: 0
      debug:
        enabled: False

pages:
  # - Home: index.md
  - Test: test.md
