site_name: Pheasant
site_url: https://pheasant.daizutabi.net/
site_description: Project documentation with MkDocs.
site_author: daizutabi

repo_url: https://github.com/daizutabi/pheasant/
edit_uri: ""

theme:
  name: rtd-pheasant
  highlightjs: true
  hljs_languages:
    - yaml
    - python

plugins:
  - pheasant

nav:
  - Home: index.md
  - User Guide:
    - Images: user-guide/images.md
    - Code: user-guide/code.md
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md
  - Test:
    - Script: test/script.py

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
#   - attr_list
